server:
    port: 11113


eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
     #关闭自我保护（开发环境）
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2

spring:
    application:
        name: deviceManagement
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/device_management?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: FCYfcy1010840201
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


     #Rabbitmq配置
    rabbitmq:
        host: 39.105.78.12
        port: 5672
        username: fcy
        password: FCYfcy1010840201
        virtual-host: /
        #开启发送端确认
        publisher-confirms: true
        #开启发送端发送失败返回（消息到达交换机，但没有到达队列）
        publisher-returns: true
        listener:
          simple:
            #采用手动ack应答
            acknowledge-mode: manual
            #最小消费者
            concurrency: 3
            #最大消费者
            max-concurrency: 8


mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.entity

#系统应用配置
userConfig:
    #线程池大小
    executorLength: 30

