server:
    port: 11112

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
     #关闭自我保护（开发环境）
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2

spring:
    application:
        name: user-management
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/user_management?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: FCYfcy1010840201
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    redis:
        database: 0
        host: localhost
        port: 6379
        password: FCYfcy1010840201
        jedis:
            pool:
                max-active: 20


mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.entity


ribbon:
    eureka:
        enabled: true
    ReadTimeout: 40000
    ConnectTimeout: 40000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: false

management:
    endpoint:
        health:
            show-details: always
#    endpoints:
#        web:
#            exposure:
#                include: '*'


#系统应用配置
userConfig:
    #阻塞队列长度
    queueLength: 60
    #线程池大小
    executorLength: 30